# Generated by Django 2.2.27 on 2022-04-13 13:56

from django.db import migrations
from rest_framework.authtoken.models import Token

# These were previously exposed to unauthenticated users. They
# will be recreated when next accessed.
def reset_tokens(apps, schema_editor):
    Token.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reset_tokens)
    ]
